### ISSUE TITLE
微软Edge Insider

### ISSUE THREAD

**Issue by mysmlz** [crimx/ext-saladict#597] opened 2019-12-18 05:54 UTC
同样是chromium内核,微软Edge Insider就太优秀了,完全不能用,什么效果都没有,大佬,可能是什么原因

![360截图16840924473273](https://user-images.githubusercontent.com/38951157/71059350-aa5c9e00-219d-11ea-917a-56958fcc4954.png)
![批注 2019-12-18 135211](https://user-images.githubusercontent.com/38951157/71059351-aa5c9e00-219d-11ea-8d02-5d2906ea60b7.png)
![批注 2019-12-18 135233](https://user-images.githubusercontent.com/38951157/71059352-aaf53480-219d-11ea-96a3-11191fc15d19.png)
![批注 2019-12-18 135136](https://user-images.githubusercontent.com/38951157/71059353-aaf53480-219d-11ea-9e44-976c49c27363.png)

**Comment by crimx** [comment] 2019-12-18 05:57
Duplicate of #585

**Closed** 2019-12-18 05:58 UTC
