### ISSUE TITLE
能否添加DeepL翻译

### ISSUE THREAD

**Issue by imlhx** [crimx/ext-saladict#1327] opened 2021-05-12 07:02 UTC
## 词典名称以及链接
DeepL
https://www.deepl.com/translator

## 沙拉查词的已有的词典为什么不能满足？

翻译不够准确，作者可以使用不同的翻译工具多测试几次便知晓
## 单词举例

Who is responsible for maintaining the product backlog?
The Product Owner (PO) “owns” the product backlog on behalf of the stakeholders, and is primarily responsible for creating it. It is not necessary for a PO to create the backlog personally – he or she may instruct the development team and/or the Scrum Master to help him/her in defining the backlog items and in estimating them. The PO is held responsible for the creation and upkeep of the product backlog. Therefore, the PO also oversees the backlog refinement process.
## 截图

![image](https://user-images.githubusercontent.com/38829117/117932075-8b325380-b332-11eb-9ee1-98e2f385f746.png)

**Comment by crimx** [comment] 2021-05-12 07:28
Duplicate of #705

**Closed by crimx** 2021-05-12 07:28 UTC
