### ISSUE TITLE
Google Translate API have limits?

### ISSUE THREAD

**Issue by yoyurec** [crimx/ext-saladict#1302] opened 2021-04-21 11:56 UTC
## Device info
 - OS: [e.g. Window10]
 - Browser Version [e.g. Chrome90]
 - Saladict Version [e.g. v7.18.1]

## Describe the bug
Looks like Google Translate API have limits for translations per time (hour?).
PS: Switching to **.cn** in options doesn't help.

## To Reproduce
1. translate lot of words for ex 40+
2. see that no more words tranlated (spinner loads, but 0 results)
 
## Expected behavior
No limits, all words are tranlated

## Screenshots
![image](https://user-images.githubusercontent.com/137919/115549629-89d0b680-a2b1-11eb-861a-f8b79003bc1f.png)

**Comment by crimx** [comment] 2021-04-21 14:16
Google translate is A/B testing its new API. I am working on new approach to adapt the changes.

**Comment by yoyurec** [comment] 2021-04-21 14:39
for now i'm using **Baidu** as a fallback

**Comment by crimx** [comment] 2021-10-31 17:57
Duplicate of #1160

**Closed** 2021-10-31 17:57 UTC
