### ISSUE TITLE
edge浏览器中点击单词，查找词典的图标和复制查找打开新标签页的图标重合

### ISSUE THREAD

**Issue by AbelKeithsun** [crimx/ext-saladict#1638] opened 2022-02-09 01:19 UTC
![image](https://user-images.githubusercontent.com/33180419/153103535-d6fc39e2-5f1d-408d-a93b-1a214da23031.png)

https://docs.min.io/

**Comment by crimx** [comment] 2022-02-09 02:01
Duplicate of #1619

**Closed as completed by crimx** 2022-02-09 02:01 UTC
